version: "3"

volumes:
  postgres_volume:

services:
  postgres:
    image: "postgres:15"
    container_name: "java-postgres"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=employee"
    ports:
      - "5555:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1m
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "web-application"
    ports:
      - "8087:8087"
    links:
      - postgres:db
    healthcheck:
      test: "curl --fail http://localhost:8087/employees || exit 1"
      interval: 1m
      timeout: 10s
      retries: 5