version: "3"

volumes:
  postgres_volume:

services:
  postgres:
    image: "postgres:15"
    container_name: "java-postgres"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=employee"
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "web-application"
    ports:
      - "8087:8087"
    links:
      - postgres:db